# Generated by Django 5.1.4 on 2024-12-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.CharField(blank=True, max_length=36, null=True)),
                ("name", models.CharField(max_length=255)),
                ("path", models.CharField(max_length=1024)),
                ("size", models.BigIntegerField()),
                ("extension", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField()),
                ("modified_at", models.DateTimeField()),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("area", models.IntegerField(blank=True, null=True)),
                ("dpi", models.IntegerField(blank=True, null=True)),
                ("exif_data", models.TextField(blank=True, null=True)),
                ("pages", models.IntegerField(blank=True, null=True)),
                ("format", models.CharField(blank=True, max_length=50, null=True)),
                ("orientation", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
