# Generated by Django 5.1.4 on 2024-12-26 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileinfo",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="fileinfo",
            name="modified_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
